# Generated by Django 5.1.7 on 2025-03-25 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Preveduvac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100)),
                ("nacionalnost", models.CharField(max_length=100)),
                ("datumRagjanje", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Zanr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100)),
                ("opis", models.CharField(max_length=1000)),
                (
                    "zanrIzbor",
                    models.CharField(
                        choices=[
                            ("N", "NOVEL"),
                            ("T", "THRILLER"),
                            ("H", "HISTORY"),
                            ("F", "FANTASY"),
                            ("B", "BIOGRAPHY"),
                            ("C", "CLASSICS"),
                            ("D", "DRAMA"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naslov", models.CharField(max_length=100)),
                ("brojStranici", models.IntegerField()),
                ("dostapnost", models.BooleanField()),
                (
                    "korica",
                    models.ImageField(blank=True, null=True, upload_to="book_photos/"),
                ),
                ("datumIzdavanje", models.DateField()),
                (
                    "avtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.author"
                    ),
                ),
                (
                    "korisnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preveduvaci",
                    models.ManyToManyField(blank=True, to="book.preveduvac"),
                ),
                ("zanrovi", models.ManyToManyField(to="book.zanr")),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ocenka",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ]
                    ),
                ),
                ("komentar", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="book.book",
                    ),
                ),
                (
                    "korisnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
